services:
  - type: web
    name: flask-ml-api
    runtime: python
    plan: free
    buildCommand: |
      pyenv install 3.9.16 -s
      pyenv global 3.9.16
      pip install -r requirements.txt
    startCommand: gunicorn app:app
